### ISSUE TITLE
Swift Package Manager Compatibility

### ISSUE THREAD

**Issue by jacobcxdev** [FLEXTool/FLEX#303]
Add a Package.swift file so that FLEX can be added to an Xcode 11 project without the use of Cocoapods.

**Comment by NSExceptional** [comment]
I would love some help with this, I've never made a non-swift SPM package. Here's what I have so far:

```swift
import PackageDescription

let package = Package(
    name: "FLEX",
    platforms: [.iOS(.v8)],
    products: [
        .library(name: "FLEX", targets: ["FLEX"])
    ],
    targets: [
        .target(
            name: "FLEX",
            path: "Classes/"
        ),
        .testTarget(
            name: "FLEXTestsMethodsList",
            dependencies: ["FLEX"],
            path: "FLEXTestsMethodsList"
        )
    ]
)
```

**Comment by jacobcxdev** [comment]
I believe that the path for the testTarget should be just `FLEXTests`.

Also, the SPM build system seems to be unable to import headers using the `#import "header.h"` notation from outside the directory of the importing source file. This means that when I tried to build FLEX as a Swift Package, there were many "header.h could not be found" errors. To see what I mean, try to build my fork.

This may be the reason that when you add `https://github.com/jacobcxdev/FLEX.git` as a Swift Package, choosing the master branch, although you can import FLEX to other source files, it has no methods etc.

**Comment by NSExceptional** [comment]
I recently pushed a commit to rename the tests target to `FLEXTests`, so the code in my comment above is outdated. Also, I have no idea whether my code is correct or not, so that's probably why header imports aren't working.

One thing I know is that it's probably going to be painful to set this up as an SPM _and_ cocoapods compatible project, since we have an explicit `FLEX.xcodeproj` and SPM likes to generate that project itself. You may want to consult the [Swift Forums](https://forums.swift.org) for more help.

**Comment by jacobcxdev** [comment]
I just tried moving everything into a single directory and it built successfully. However, I'm still running into the issue where you can import FLEX into a Swift project but it has no methods available (and when you cmd-click the import statement and choose "Jump to definition", it takes you to a blank file).

**Comment by NSExceptional** [comment]
@jacobcxdev Still having that issue? If so, can you please make a new issue?
