### ISSUE TITLE
Add Swift example project

### ISSUE THREAD

**Issue by ryanolsonk** [FLEXTool/FLEX#314]
The updated version of [UIKit-Catalog](https://developer.apple.com/documentation/uikit/views_and_controls/uikit_catalog_creating_and_customizing_views_and_controls) is Swift and may be a nicer example project since developers have largely moved to swift at this point. We'll keep the framework obj-c only for compatibility with obj-c only projects.

**Comment by NSExceptional** [comment]
I've kinda wanted to write our own since UICatalog features an awful mega-storyboard. Maybe a sample "social network" app or something that just pulls things from a database and Keychain—it could showcase the ability to run queries / modify the keychain / etc from within FLEX. Right now, the app does little but showcase the view inspection capabilities (along with the things we hard-code, like networking and logging).

I'll probably do this in my free time at some point this year, so I'll assign myself.

**Comment by vincivinci77** [comment]
https://github.com/Flipboard/FLEX/labels/enhancement

**Comment by NSExceptional** [comment]
New project should be named FLEXample
