### ISSUE TITLE
Debug builds with FLEX are rejected by Apple for TestFlight

### ISSUE THREAD

**Issue by chilimovpasha** [FLEXTool/FLEX#474]
Hello everyone!
I want to upload debug build with Flex (pod has been connected only for debug and imported if DEBUG), but it is rejected as invalid binary with text below:

> ITMS-90338: Non-public API usage - The app references non-public selectors in Frameworks/FLEX.framework/FLEX: _setWidth:, continuousCorners, setContinuousCorners:. If method names in your source code match the private Apple APIs listed above, altering your method names will help prevent this app from being flagged in future submissions. In addition, note that one or more of the above APIs may be located in a static library that was included with your app. If so, they must be removed.

Could you please assist me?))

**Comment by tcpthecode** [comment]
Apple won't allow to upload binary that implemented private APIs. 
If you want to distribute IPA for beta testing or internal using, you can choose other options like: Diawi, own https host with install over-the-air capability

**Comment by NSExceptional** [comment]
Why do you want to upload a build with FLEX in it?

**Comment by chilimovpasha** [comment]
Basically I want to testers could be able to send me logs files and see network interactions

**Comment by NSExceptional** [comment]
There are ways to enable exporting of logs without FLEX. As for network activity, it is very unusual for a tester to need to see that.

If you are just distributing the app to other coworkers or people part of your organization, and they need access to FLEX, it is probably better to just send them the Ad-Hoc signed IPA yourself

**Comment by teerayuthjanopas** [comment]
@chilimovpasha Please try Distribution via Firebase Distribution. You won't waiting apple process bundle for testing.

**Comment by chilimovpasha** [comment]
Sorry, I do not have access to the internet. Thanks for advices, starting use firebase distribution)

**Comment by asifmohd** [comment]
I've removed the private API usage in my forked repo on this branch: [`remove_private_api_usage`](https://github.com/asifmohd/FLEX/tree/remove_private_api_usage)

I was able to validate that uploading a testflight build with these changes, lets it pass Apple's automated verification, i.e. I don't see the error mentioned in the first post anymore.

Haven't seen any UI being broken so far basis my limited testing on an iOS 14 device.

Happy to raise this as a PR if `NSExceptional` is willing to accept the removal as a fix, considering the issue is marked as `won't fix` right now. (Also a huge thank you for the amazing tool team 🙇 )

Anyways, just wanted to post a comment here, so that anyone who also has a need to use FLEX in testflight builds, can do so (at their own risk) by using the forked repo mentioned here. 🙏

**Comment by NSExceptional** [comment]
Hi all,

I have since updated the license as I said I would in another issue. If you submit App Store builds with FLEX, you are in violation of our license. FLEX is intended for your use only, and not that of end-users.

**Comment by asifmohd** [comment]
Oh sorry, I wasn't aware of the update to the license 🙇 . Let me know if I should remove my comment above?

To add: right now we are using TestFlight builds so that we can bypass the 100 device limit apple imposes on us. We have > 50 QAs, ~80 iOS devs at my workplace. Hence it's difficult to register each device for each user, with many users having multiple devices. Hence we use TestFlight for internal distribution and for QA. Devs have been using FLEX on debug builds daily for network requests, and there have been asks by devs/QAs to support network request debugging on testflight builds as well, since the FLEX tool makes it so convenient.

The intention here wasn't to ask the team to fix it or accept a PR. I just wanted to ensure if someone else stumbles upon this and needs this, maybe they can use the fork, as long as they are *ok* dealing with the repercussions/bugs of the fork, or it being not up to date etc.

Would it still be a violation of the license if we never send FLEX builds to appstore to actual users/customers, and only use it for TestFlight builds for our internal users? Would it make sense to clarify the same in the LICENSE if so?

**Comment by NSExceptional** [comment]
I see, that is a unique scenario. I may mention your fork in the readme for rare cases like this then.

> Would it still be a violation of the license if we never send FLEX builds to appstore to actual users/customers, and only use it for TestFlight builds for our internal users?

I'm gonna say no, because the license specifically says "App Store," and the spirit of the rule was to avoid showing FLEX to end users :)

> Would it make sense to clarify the same in the LICENSE if so?

I will definitely clarify it on this behalf! Thank you for bringing a new use case to my attention.

(No need to remove your comment btw)

**Comment by ziizop** [comment]
Please tell me how to configure Flex for firebase App Distribution, now I have a problem, I distribute for testers, through App Distribution , but there is no Flex
