### ISSUE TITLE
Bookmarks fail to persist across sessions

### ISSUE THREAD

**Issue by badger200** [FLEXTool/FLEX#506]
### Environment
- Platform+version: **iOS 12.4** 
- FLEX version: **4.2.2** 

### Bug Report

I have never seen the Add to Bookmarks actually save a bookmark. Aren’t they supposed to persist across app sessions? Or am I misunderstanding?

**Comment by NSExceptional** [comment]
No, bookmarks do not persist across launches. Bookmarks are a way of saving an object for quick access later while the app is still running.

I am thinking of adding a way to bookmark a key path (ie `UIApplication.sharedApplication.delegate`), but that won't be very useful for views and the like since there aren't stable key paths to views with no references to them besides their superviews
