### ISSUE TITLE
Firebase logging response not captured by network monitor

### ISSUE THREAD

**Issue by pwadowski** [FLEXTool/FLEX#603]
### Environment
- Platform+version: **iOS 15.4**
- FLEX version: **4.7.0**

### Bug Report

I tried FLEX for the first time and noticed that Network History doesn't work in my project. All of the endpoints of the project backend and Firebase endpoints stuck on _Awaiting response_ status. I have tried to manipulate with response cache limit but it didn't helped. I installed FLEX through Cocoapods and checked both on simulator and physical device. 

<img width="50%" src=https://user-images.githubusercontent.com/39055111/168520510-d29aa55b-f05f-44e6-ae35-e568eeceeb5f.png>
<img width="50%" src=https://user-images.githubusercontent.com/39055111/168520590-4a0dd950-848a-4b95-8449-b997dfcaf748.png>

**Comment by NSExceptional** [comment]
Thanks! I'll look into this, have been seeing the same thing on my end with firebase logging.

**Comment by LovekeshBhagat-TUL-MP** [comment]
I am facing same issue, I am using URL session

**Comment by NSExceptional** [comment]
Solved! TLDR: add `firebase_performance_collection_deactivated` to your `Info.plist` and set it to `NO`

https://firebase.google.com/docs/perf-mon/disable-sdk?platform=ios

**Comment by burakCokyildirim** [comment]
> Solved! TLDR: add `firebase_performance_collection_deactivated` to your `Info.plist` and set it to `NO`
> 
> https://firebase.google.com/docs/perf-mon/disable-sdk?platform=ios

I want to suggest an additional solution for this issue.

I added the relevant key to info.plist, but the problem was not resolved. But when I removed FirebasePerformance from the Project, the problem was solved.

if you are using FirebasePerformance, you can add FirebasePerformance to your Podfile with setting configuration like below.
`pod 'FirebasePerformance', '7.4.0', :configurations => ["Release"]`
(7.4.0 is the specific version we use. You can change it according to your needs.)

In this way, you can avoid the "awaiting response" problem in Debug configuration like me.
